services:
  - type: web
    name: attendmax-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    healthCheckPath: /
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: app.py
      - key: PYTHON_VERSION
        value: 3.11.8
      - key: FIREBASE_CREDENTIALS
        sync: false # This will be manually added in Render dashboard 